parameters:
#    vitarian_admin.example.class: Vitarian\AdminBundle\Example

services:
#    vitarian_admin.example:
#        class: %vitarian_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#vitarian.admin.admin.post:
#        class: Vitarian\AdminBundle\Admin\PostAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: vitarian, label: post }
#        arguments:
#            - ~
#            - Vitarian\ReceptyBundle\Entity\Post
#            - VitarianAdminBundle:PostAdmin