parameters:
#    vitarian_recepty.example.class: Vitarian\ReceptyBundle\Example

services:
#    vitarian_recepty.example:
#        class: %vitarian_recepty.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    vitarian_services.search_engine:
        class: Vitarian\ReceptyBundle\Services\Search
        arguments:
            - "@doctrine.orm.entity_manager"