Vitarian\ReceptyBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        body:
            type: text
        published:
            type: datetime
    lifecycleCallbacks: {  }
